services:
  db:
    image: postgres:16
    container_name: expense_db
    environment:
      POSTGRES_USER: expense
      POSTGRES_PASSWORD: expense
      POSTGRES_DB: expense
    ports:
      - "5432:5432"
    volumes:
      - expense_db_data:/var/lib/postgresql/data

volumes:
  expense_db_data:
